### ISSUE TITLE
Apt failes when aptcacher is not available

### ISSUE THREAD

**Issue by john-arvid** [edgd1er/ntopng-docker#1]
Thank you for this docker setup.
I noticed that when I did the 'docker-compose up -d' it failed to get packages.
It looks like the if check in Dockerfile.all doesn't work.
I commented out that part and it compiled ok.

**Comment by edgd1er** [comment]
Thanks for your interest :)
I changed the test to remove the 01proxy file, but for the moment, I can not validate locally as the cache is corrupted and I cannot use it for the moment. I'll let github actions publish the new image, let me know if you have still issues with the proxy ;)

**Comment by edgd1er** [comment]
@john-arvid
I check that the proxy is now removed when set for build stage. Github image building does not set the aptCacher, so the issue shoudl be fixed.
